In [1]:
import torch
import torch.nn as nn

In [3]:
# input
torch.manual_seed(42)
inputs = torch.tensor([1.0, 2.0, 3.0])

In [5]:
neuron = nn.Linear(in_features=3, out_features=1)

In [7]:
output = neuron(inputs)

In [9]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [11]:
# verify ... forumula
neuron.weight @ inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)

In [13]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)